apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-argoset
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
